name: flutter_task_manager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  retrofit: ^4.4.1
  logger: any  #for logging purpose
  flutter_local_notifications: ^18.0.0
  flutter_animate: ^4.5.0
  shared_preferences: ^2.3.2
  go_router: ^14.4.1
  json_annotation: ^4.9.0
  gap: ^3.0.1
  intl: ^0.19.0
  flutter_localization: ^0.2.2
  freezed_annotation: ^2.4.4
  dio: ^5.1.1
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  flutter_gen_runner:
  freezed: ^2.5.7
  json_serializable: ^6.0.0


flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/svg/
    - assets/png/
flutter_intl:
  enabled: true

